// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211129024502_LatestTables")]
    partial class LatestTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("API.Entities.Accrual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EmployeeAdditional")
                        .HasColumnType("REAL");

                    b.Property<double>("EmployerAdditional")
                        .HasColumnType("REAL");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberID")
                        .HasColumnType("TEXT");

                    b.Property<double>("Productivity")
                        .HasColumnType("REAL");

                    b.Property<double>("Redundancy")
                        .HasColumnType("REAL");

                    b.Property<double>("SalarySacrifice")
                        .HasColumnType("REAL");

                    b.Property<double>("Spouse")
                        .HasColumnType("REAL");

                    b.Property<string>("SuperFund")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SuperGuarantee")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("USI")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tblAccrual");
                });

            modelBuilder.Entity("API.Entities.DataRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MYOB")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tblDataRecords");
                });

            modelBuilder.Entity("API.Entities.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomList2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locality")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherGivenName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayrollID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tblEmployees");
                });

            modelBuilder.Entity("API.Entities.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fullname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberID")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayrollID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuperUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("TFN")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tblPayroll");
                });
#pragma warning restore 612, 618
        }
    }
}
